### ISSUE TITLE
Use App node instead of a Login node

### ISSUE THREAD

**Issue by mahitha-raj** [Submissions/topmed-tools#1]
Explore the possibility of using an app node for the bash wrapper script instead of the current practice of using the login node.

*Using this issue as an example for ZenHub*

**Comment by walkerh** [comment]
I only use a login nodes for data transfer with my laptop.

Example:
```
rsync my_directory sug-login1.hgsc.bcm.edu:/groups/submissions/users/hale
```

On my laptop, I have this script:
```bash
(main) bin$ cat sa1
#!/usr/bin/env bash

login_host=${DEFAULT_SUG_LOGIN:-$s4}

ssh -t $login_host ssh sug-app1 "$@"
```

This is equivalent to:
```
ssh -t sug-login4.hgsc.bcm.edu ssh sug-app1
```

The `-t` on the outer `ssh` says:
> Do not allocate a pseudo-terminal just pass the connection through to the inner ssh, which will allocate the one pseudo-terminal.

**Comment by walkerh** [comment]
@eskinner What are your thoughts on this? Should we document this as internal SOP?

**Comment by eskinner** [comment]
@walkerh I only use login nodes, so I don't have much of an opinion except that switching over might confuse me.

**Comment by walkerh** [comment]
@mahitha-raj add a summary of this convesation to `cram-processing-tools/docs` and then close this issue.
