### ISSUE TITLE
Test `topmed_automation`

### ISSUE THREAD

**Issue by itsmarcy** [Submissions/topmed-tools#6]
`topmed_automation` has been merged.

It would be nice to test this so we can iron out the bugs and do the fixes.

**Reminder**:
- The user is still responsible for checking if aspera has space.
- Will only take the user up to submitting the crams for validation. It does **not** copy over the crams or ensures that there were no validation errors.
   - Pretty much up to step 10 from [here](https://github.com/Submissions/cram-processing-tools/blob/master/topmed.sh).
- `shepherd` has to be updated to the latest changes for this to work.

For docs on this script, [view here](https://github.com/Submissions/cram-processing-tools/blob/master/docs/topmed_automation.md).

If there are any bugs, create issues.

Once we tested this, we can then move on in automating rest of the steps!

**Comment by mahitha-raj** [comment]
Light-weight test files have been created.  Closing this issue because it is a part of #4.
